# Generated by Django 5.0.2 on 2024-02-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediMeter.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediMeter.user')),
            ],
        ),
    ]
