# Generated by Django 5.0.2 on 2024-03-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0003_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
