# Generated by Django 5.0.3 on 2024-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0004_remove_user_age_remove_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiver',
            old_name='contact_details',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='name',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='brings_medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='pillbox_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
