# Generated by Django 5.0.2 on 2024-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0007_medication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
