# Generated by Django 5.0.2 on 2024-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0008_caregiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dietary_restrictions',
            field=models.TextField(default='', max_length=20),
        ),
    ]
