# Generated by Django 5.0.2 on 2024-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0010_medication_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='tabletcount',
            field=models.IntegerField(default=0),
        ),
    ]
