# Generated by Django 5.0.2 on 2024-04-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0012_medication_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='missed_doses',
            field=models.IntegerField(default=0),
        ),
    ]
