# Generated by Django 5.0.2 on 2024-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0015_alter_medication_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='picture',
            field=models.ImageField(default='media/medication_pics/default.jpg', upload_to='media/medication_pics/'),
        ),
    ]
