# Generated by Django 5.0.2 on 2024-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0017_alter_medication_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='medication_pics/'),
        ),
    ]
