# Generated by Django 5.0.2 on 2024-04-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0018_alter_medication_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
