# Generated by Django 5.0.2 on 2024-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediMeter', '0019_alter_medication_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
    ]
